services:
  auth-db:
    extends:
      file: db/compose.yaml
      service: auth-db

  post-db:
    extends:
      file: db/compose.yaml
      service: post-db

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      AUTH_DATABASE_URL: "${AUTH_DATABASE_URL}"
      APP_ENV: prod
      PORT: 8080
    depends_on:
      auth-db:
        condition: service_healthy

  post:
    build:
      context: .
      dockerfile: services/post/Dockerfile
    container_name: post-service
    restart: unless-stopped
    environment:
      POST_DATABASE_URL: "${POST_DATABASE_URL}"
      APP_ENV: prod
      PORT: 8080
    depends_on:
      post-db:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: gateway-service
    restart: unless-stopped
    environment:
      APP_ENV: prod
      PORT: 8080
      AUTH_SERVICE_URL: "http://auth:8080"
      POST_SERVICE_URL: "http://post:8080"
    ports:
      - "3030:8080"
