name: Deploy
on:
  push:
    branches: [main]
    paths: ["deploy/**"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync deploy configs
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/admin/twomice
            git pull origin main
            docker pull ghcr.io/mouseburrow/twomice-frontend:${ENV:-prod-latest}
            docker compose -f deploy/docker-compose.prod.yaml up -d nginx
            docker compose -f deploy/docker-compose.test.yaml up -d
